project_id = "hfzysrftppvxkxfgcumw"

[functions.import-hubspot-contacts]
verify_jwt = false

[functions.contact-analytics]
verify_jwt = false

[functions.import-ads-changes]
verify_jwt = false

[functions.generate-campaign-narrative]
verify_jwt = false

[functions.import-hubspot-deals]
verify_jwt = false

[functions.fetch-ctm-calls]
verify_jwt = false

[functions.parse-document]
verify_jwt = false

[functions.import-google-ads-performance]
verify_jwt = false

[functions.import-google-ads-geo]
verify_jwt = false

[functions.fetch-ctm-account]
verify_jwt = false

[functions.import-hubspot-leads]
verify_jwt = false
